- name: Install unattended-upgrades
  apt:
    name: unattended-upgrades
    update_cache: yes
    cache_valid_time: 600 # 10 minutes

- name: Install unattended-upgrades apt config file
  template:
    src: 50unattended-upgrades.j2
    dest: /etc/apt/apt.conf.d/50unattended-upgrades

# This file is not automatically created on all Ubuntu systems.
- name: Activate unattended-upgrades
  copy:
    src: 20auto-upgrades
    dest: /etc/apt/apt.conf.d/20auto-upgrades
