- hosts: all
  gather_facts: false
  roles:
    - role: bootstrap-python

- hosts: all
  vars_files:
    - ../config/ansible-playbooks.yml
  vars:
    hostname: gitlab
    unattended_upgrade_origins:
      - packages.gitlab.com/gitlab/gitlab-ce:bionic
  roles:
    - role: common
    - role: apt-https
    - role: ufw
    - role: gcloud-logging
  handlers:
    - import_tasks: handlers/gitlab.yml
  tasks:
    - import_tasks: tasks/gitlab-ufw-rules.yml
    - import_tasks: tasks/gitlab.yml
    - import_tasks: tasks/gcloud-sdk.yml
    - import_tasks: tasks/backups.yml
